#!/bin/zsh 

ghci grammar_for_types.hs


# --e.g. 
# *Main> eqls (Arr (Arr Num (Arr Num Num)) Num) (Arr Num Num)
# False
# *Main> eqls (C Num) (C (C Num))
# False
# *Main> eqls (Arr Num Num) (C (C (Arr Num Num)))
# True